fix some errors. more errors to be fixed:
cmd/utility_linux.go:22:6: `decodeString` is unused (deadcode)
func decodeString(fileContent string) (string, error) {
     ^
cmd/utility_linux.go:105:6: `hashFileMD5` is unused (deadcode)
func hashFileMD5(filePath string) (string, error) {
     ^
cmd/phocus.go:34:17: Error return value of `ReadScoringData` is not checked (errcheck)
        ReadScoringData()
                       ^
cmd/remote.go:284:14: Error return value of `hasher.Write` is not checked (errcheck)
        hasher.Write([]byte(password))
                    ^
cmd/scoring.go:22:16: Error return value of `reportScore` is not checked (errcheck)
                                reportScore()
                                           ^
cmd/configs.go:52:2: ineffectual assignment to `configFile` (ineffassign)
        configFile = ""
        ^
cmd/utility.go:118:2: S1000: should use for range instead of for { select {} } (gosimple)
        for {
        ^